### ISSUE TITLE
What's the meaning of ::this ?

### ISSUE THREAD

**Issue by DangerousSquid** [mxstbr/login-flow#16]
Hi Max Stoiber,

I'm just trying to figure out what's the meaning of `::this` 
https://github.com/mxstbr/login-flow/blob/master/js/components/pages/LoginPage.react.js#L28
I never saw something like that before.

thanks,
Gab

**Comment by geakstr** [comment]
This is new fuction binding syntax in ES7 https://babeljs.io/blog/2015/05/14/function-bind

**Comment by DangerousSquid** [comment]
Thanks !

**Comment by mxstbr** [comment]
Seems like @geakstr was a lot faster than me, thanks for the quick answer!
