### ISSUE TITLE
Encrypt password on the frontend before sending the request

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/login-flow#2]
Security reasons

**Comment by geakstr** [comment]
Encryption on the client is not secure, isn't it? I think server must be available only through SSL and that's enough.

**Comment by mxstbr** [comment]
The best way is to encrypt on both the client and the server, so the network and server have no idea of the plaintext password/usernames. Avoids MITM in the local WiFi etc.

**Comment by geakstr** [comment]
I'm not an expert in security, but what about next example?

1. Client encrypt password and sent it to server over SSL
2. MITM in the local WiFi intercepts traffic and get encrypted password
3. Hacker send encrypted password to server and server accept this

One profit is hacker not to know about original password, yes?

**Comment by mxstbr** [comment]
Yes exactly, while the hacker can still replay the request, he doesn't have the plaintext password. This means we potentially save the user, who is highly likely using the same password across a number of services, from complete ownage.

**Comment by geakstr** [comment]
Thank you for explanation. What secure methods to one-way encryption on client-side?

**Comment by mxstbr** [comment]
bcrypt all the way. (see [here](http://codahale.com/how-to-safely-store-a-password/) or google around a bit as to why)

**Comment by geakstr** [comment]
Ok 👍

**Comment by mxstbr** [comment]
By the way, I'd _love_ a PR for this.

**Comment by geakstr** [comment]
Yeah, I worked on this today for my app, and do this for your project. Check this https://github.com/mxstbr/login-flow/pull/7

**Comment by marcospgp** [comment]
@mxstbr Doesn't https protect against a man in the middle attack? (Such as someone in the local wifi network like you mentioned)

**Comment by TheCeloReis** [comment]
> @mxstbr Doesn't https protect against a man in the middle attack? (Such as someone in the local wifi network like you mentioned)

This is true, this aproach currently is over engineeringwith client security

**Comment by hagridleitc** [comment]
Jun 2024, I received this question when I joined the interview. I think this approach is over-engineering also. Instead, you can consider logging in with **SSO** via Google, Github,...
