### ISSUE TITLE
I can't find the request.js

### ISSUE THREAD

**Issue by mscalessio** [mxstbr/login-flow#20]
Thank's bro for this! it's awesome.
Could you help me to correctly setup this for my purpose?

I wold like to make some changes:
- the only page visible to non-logged-in user is /login
- make a real HTTP req (with request.js missing file) store the session variable for calling the API
- redirect to /dashboard 

Pleaseee 👍

**Comment by hellojebus** [comment]
By "request.js", the developer mean this library:

https://github.com/request/request

Once you npm install, as usual, you just `import require from 'request';`

**Comment by mxstbr** [comment]
That library doesn't actually work on the front end, you'll have to use `xhr` or `axios` or some other requesting library. There's tons of them!
