### ISSUE TITLE
Looks complicated?

### ISSUE THREAD

**Issue by scheung38** [mxstbr/login-flow#21]
I just want to grab a login react jsx form but this seems complicated. Could you indicate what is the minimum files needed for me to login (no registration form needed) as I will have just a single username and hashed password. Thanks

**Comment by mpaarating** [comment]
This is probably the wrong forum to be asking for that. A bit of googling brought up this article which should help you out! https://auth0.com/blog/adding-authentication-to-your-react-flux-app/
