### ISSUE TITLE
PR: Add flow support

### ISSUE THREAD

**Issue by amilajack** [mxstbr/login-flow#25]
Using Flow along with react can provide for a great workflow. Many popular boilerplate projects, like create-react-app are now supporting it. Would a PR for adding it be welcome?

**Comment by mxstbr** [comment]
This project isn't really maintained anymore, and is quite out of date with `react-boilerplate`. I'd much rather update it to use `react-boilerplate` v3, as a showcase kinda thing!

**Comment by amilajack** [comment]
Great! Thanks for clarifying!
