### ISSUE TITLE
app running forever on port 3000

### ISSUE THREAD

**Issue by sukeesh** [mxstbr/login-flow#34]

**Comment by yarnball** [comment]
+ 1 Also having this issue.

**Comment by mxstbr** [comment]
`CTRL+C` should stop the process, if that doesn't work for you see this SO answer: https://stackoverflow.com/questions/11583562/how-to-kill-a-process-running-on-particular-port-in-linux

**Comment by yarnball** [comment]
Killing the port does not solve the issue. Must have to do with it being a persistant app. For example, it does not appear when you're in incognito mode.

**Comment by mxstbr** [comment]
Oh you mean the caching? Yeah it's cached with AppCache and ServiceWorker

```
chrome://appcache-internals
chrome://serviceworker-internals
```

Delete the localhost:3000 entry on both sites to get rid of the cache.

**Comment by yarnball** [comment]
So everytime I make a change to the code, I should delete both of them?

**Comment by mxstbr** [comment]
No, in development it updates automatically, only when you run it in production mode.

**Comment by yarnball** [comment]
How about for safari? Worth adding to the readme, as this will probably happen to lots

EDIT: for safari:

1. Enable developer menu (https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html#//apple_ref/doc/uid/TP40007874-CH2-SW1)

2. Developer menu > `Disable Cache`

3. Developer menu > `Empty Cache`

**Comment by tnpriyanka12** [comment]
yes I have killed all operation running. Closed and reopened my terminal. Deleted the whole folder that i forked from here.  Still this happens. any other leads?
