### ISSUE TITLE
How to set a real URL?

### ISSUE THREAD

**Issue by yarnball** [mxstbr/login-flow#35]
Hi,

I may have missed this- seems a basic question. I would like to use this with an actual server. So how would i change the it so it passes the username/password to a URL instead? Thanks

**Comment by mxstbr** [comment]
Replace [this import](https://github.com/mxstbr/login-flow/blob/44b34885d0bbfac18d57bd7879f886f022817774/js/utils/auth.js#L1) with your favorite XHR request library, for example `xhr`:

```diff
-import request from './fakeRequest';
+import request from 'xhr';
```

Change the [`request.post` calls](https://github.com/mxstbr/login-flow/blob/44b34885d0bbfac18d57bd7879f886f022817774/js/utils/auth.js#L22) in that file to use your real URL:

```diff
-request.post('/login')
+request.post('myserver.com/login')
```
