### ISSUE TITLE
Why not on onEnter on the route

### ISSUE THREAD

**Issue by weblancaster** [mxstbr/login-flow#5]
Hi @mxstbr thanks for sharing this repo I got say was very time consuming to find the best way to do a login flow so I'm sure this repo will be very useful for a lot of people.

My case I use `onEnter` isn't that a better option since React-Router give us the option and that way we keep the component `dashboard` a bit more clean without the logic to check the auth?

let me know your thoughts.

**Comment by mxstbr** [comment]
That sounds like a very good idea to be honest, I'd **love** a PR!
